#Do not change this version
version: 1.2

# Fill the inventory
FillItem:
  enable: true
  item:
    material: BLUE_STAINED_GLASS_PANE
    amount: 1
    display_name: ' '
    lore:
      - ''

gui_settings:
  name: 'Linked Block Settings'
  # Available sizes: 9, 18, 27, 36, 45, 54
  size: 27

special_items:
  linked_block:
    status_ok:
      store:
        material: '{BLOCK}'
        display_name: ''
        amount: 1
        # Available placeholders {BLOCK_X}, {BLOCK_Y}, {BLOCK_Z}, {BLOCK_WORLD}
        lore:
          - '&6World: &7{LOCATION_WORLD}'
          - '&6X: &7{LOCATION_X}'
          - '&6Y: &7{LOCATION_Y}'
          - '&6Z: &7{LOCATION_Z}'
      furnace:
        material: '{BLOCK}'
        display_name: ' '
        amount: 1
        lore:
          - '&6World: &7{LOCATION_WORLD}'
          - '&6X: &7{LOCATION_X}'
          - '&6Y: &7{LOCATION_Y}'
          - '&6Z: &7{LOCATION_Z}'
      void:
        material: 'BARRIER'
        display_name: '&cVoid Chest'
        amount: 1
        lore:
          - 'The item will get thrown to the void!'
          - ''
    missing:
      store:
        material: 'BEDROCK'
        display_name: '&cThe block is missing!'
        amount: 1
        # Available placeholders {BLOCK_X}, {BLOCK_Y}, {BLOCK_Z}, {BLOCK_WORLD}
        lore:
          - ''
          - '&6The block should be Chest, Shulker Box, Barrel, etc!'
          - ''
          - '&cWorld: &7{LOCATION_WORLD}'
          - '&cX: &7{LOCATION_X}'
          - '&cY: &7{LOCATION_Y}'
          - '&cZ: &7{LOCATION_Z}'
          - ''
          - '&6You can either remove this or place back the block!'
      furnace:
        material: 'BEDROCK'
        display_name: '&cThe block is missing!'
        amount: 1
        lore:
          - ''
          - '&6The block should be Furnace, Blast Furnace, Smoker!'
          - ''
          - '&cWorld: &7{LOCATION_WORLD}'
          - '&cX: &7{LOCATION_X}'
          - '&cY: &7{LOCATION_Y}'
          - '&cZ: &7{LOCATION_Z}'
          - ' '
          - '&6You can either remove this or place back the block!'
    slot: 4
  smelt:
    # Show this item if all the block status are fine ( not missing )
    enabled:
      item:
        material: REDSTONE_TORCH
        amount: 1
        display_name: '&aSmelt Item'
        # Available placeholders {SMELT_COST}: return the cost that set in config.yml
        lore:
          - '&6Enable: &atrue'
          - ' '
          - '&7- Auto smelt while transferring the item'
          - '&7- Cost: {SMELT_COST}'
    disabled:
      item:
        material: LEVER
        amount: 1
        display_name: '&aSmelt Item'
        lore:
          - '&6Enable: &4false'
          - ' '
          - '&7- Auto smelt while transferring the item'
          - '&7- Cost: {SMELT_COST}'
    no_permission:
      item:
        material: RED_STAINED_GLASS_PANE
        amount: 1
        display_name: '&aSmelt Item'
        lore:
          - '&&cYou don''t have permission to enable this'
          - ' '
          - '&7- Auto smelt while transferring the item'
          - '&7- Cost: {SMELT_COST}'
    disabled_by_server:
      item:
        material: RED_STAINED_GLASS_PANE
        amount: 1
        display_name: '&aSmelt Item'
        lore:
          - '&cThis function is disabled by the server'
          - ' '
          - '&7- Auto smelt while transferring the item'
          - '&7- Cost: {SMELT_COST}'
    slot: 12
  remove_block:
    item:
      material: RED_STAINED_GLASS_PANE
      amount: 1
      display_name: '&cRemove Block'
      lore:
        - ''
    slot: 14
# You can add extra item for decoration in this section by following the format
items:
  1:
    item:
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      display_name: ' '
      lore:
        - ' '
    slot: 0
  2:
    item:
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      display_name: ' '
      lore:
        - ' '
    slot: 8
  3:
    item:
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      display_name: ' '
      lore:
        - ' '
    slot: 18
  4:
    item:
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      display_name: ' '
      lore:
        - ' '
    slot: 26
