#Do not change this version
version: 1.1

# Fill the inventory
FillItem:
  enable: true
  item:
    material: BLUE_STAINED_GLASS_PANE
    amount: 1
    display_name: ' '
    lore:
      - ''

gui_settings:
  name: 'Linked Block Settings'
  # Available sizes: 9, 18, 27, 36, 45, 54
  size: 27

special_items:
  linked_block:
    item:
      amount: 1
      display_name: '&r&6{PLAYER}'
      # Available placeholders {BLOCK_X}, {BLOCK_Y}, {BLOCK_Z}, {BLOCK_WORLD}
      lore:
        - ''
    slot: 4
  smelt:
    # Show this item if all the block status are fine ( not missing )
    enabled:
      item:
        material: REDSTONE_TORCH
        amount: 1
        display_name: '&aSmelt Item'
        # Available placeholders {SMELT_COST}: return the cost that set in config.yml
        lore:
          - '&6Enable: &atrue'
          - ' '
          - '&7- Auto smelt while transferring the item'
          - '&7- Cost: {SMELT_COST}'
    disabled:
      item:
        material: LEVER
        amount: 1
        display_name: '&aSmelt Item'
        lore:
          - '&6Enable: &4false'
          - ' '
          - '&7- Auto smelt while transferring the item'
          - '&7- Cost: {SMELT_COST}'
    no_permission:
      item:
        material: RED_STAINED_GLASS_PANE
        amount: 1
        display_name: '&aSmelt Item'
        lore:
          - '&&cYou don''t have permission to enable this'
          - ' '
          - '&7- Auto smelt while transferring the item'
          - '&7- Cost: {SMELT_COST}'
    disabled_by_server:
      item:
        material: RED_STAINED_GLASS_PANE
        amount: 1
        display_name: '&aSmelt Item'
        lore:
          - '&cThis function is disabled by the server'
          - ' '
          - '&7- Auto smelt while transferring the item'
          - '&7- Cost: {SMELT_COST}'
    slot: 12
  remove_block:
    item:
      material: RED_STAINED_GLASS_PANE
      amount: 1
      display_name: '&cRemove Block'
      lore:
        - ''
    slot: 14
# You can add extra item for decoration in this section by following the format
items:
  1:
    item:
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      display_name: ' '
      lore:
        - ' '
    slot: 0
  2:
    item:
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      display_name: ' '
      lore:
        - ' '
    slot: 8
  3:
    item:
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      display_name: ' '
      lore:
        - ' '
    slot: 18
  4:
    item:
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      display_name: ' '
      lore:
        - ' '
    slot: 26
